name: Run Gradle check

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: eskatos/gradle-command-action@v2
      name: gradle check
      with:
        arguments: check
