name: Run Gradle check

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - uses: kiancross/checkstyle-annotations-action@v1
    - uses: gradle/gradle-build-action@v2
      name: gradle check
      env:
        CI: true
      with:
        arguments: check -Pheadless=true
